import { Telegraf, Markup, Context } from 'telegraf';
import { config } from './config.js';
import bs58 from 'bs58';
import { Keypair } from '@solana/web3.js';
import { createWallet, getWallet, getWallets, deleteWallet } from './store.js';
import { connection, masterKeypair, masterBalance, solBalance, shortKey, explorerTx, createCoin, buy, sell, tokenBalance, tokenAnalytics, sendSol, PublicKey, BN } from './solana.js';

const bot = new Telegraf(config.telegramBotToken);
const authorized = new Set<number>();
const sessions = new Map<number,{action:string;data:Record<string,string>}>();
const locks = new Set<string>();

function uid(ctx:Context): number { return ctx.from?.id ?? 0; }
function isOwner(ctx:Context): boolean { return uid(ctx) === config.ownerTelegramId; }
function auth(ctx:Context): boolean { return authorized.has(uid(ctx)); }
function ownerGuard(ctx:Context): boolean { if (!isOwner(ctx)) { void ctx.reply('❌ Owner-only command.'); return false; } return true; }
function mainMenu() { return Markup.inlineKeyboard([[Markup.button.callback('🚀 Create Coin','create'),Markup.button.callback('💰 Balances','balances')],[Markup.button.callback('👛 Treasury','wallets'),Markup.button.callback('🛒 Buy','buy')],[Markup.button.callback('💸 Sell','sell'),Markup.button.callback('📊 Analytics','analytics')],[Markup.button.callback('📤 Payout','payout'),Markup.button.callback('⚙️ Admin','admin')]]); }
function fmtError(e:unknown):string { const s=e instanceof Error?e.message:String(e); if(/insufficient/i.test(s)) return 'Insufficient SOL balance.'; if(/blockhash/i.test(s)) return 'Blockhash expired. Refresh and try again.'; if(/graduat/i.test(s)) return 'This token has graduated. Bonding-curve trading is unavailable.'; if(/slippage/i.test(s)) return 'Slippage exceeded. Refresh the quote and try again.'; return s.slice(0,700); }
function requireAuth(ctx:Context): boolean { if(!auth(ctx)){void ctx.reply('🔐 Access required.\nUse /access <key>');return false;}return true; }
function parsePositive(raw:string):number { const n=Number(raw); if(!Number.isFinite(n)||n<=0) throw new Error('Invalid amount.'); return n; }
function walletKey(id:string){return `wallet:${id}`;}
function loadKeypair(id:string): Keypair { const w=getWallet(id); if(!w) throw new Error('Wallet not found.'); return Keypair.fromSecretKey(bs58.decode(w.secretKey)); }

bot.start(async ctx=>{ if(!auth(ctx)) return ctx.reply('🔐 MaterBabe Coin Kirkinator\nAccess required.\nUse /access <key>'); await ctx.reply('🪙 MaterBabe Coin Kirkinator\nCreated by: YYLuccys Mom\nMainnet: ONLINE',mainMenu()); });
bot.command('access',async ctx=>{const key=ctx.message.text.split(/\s+/).slice(1).join(' ').trim();if(key&&key===config.accessKey){authorized.add(uid(ctx));return ctx.reply('✅ Access granted.',mainMenu());}return ctx.reply('❌ Invalid access key.');});
bot.command('help',async ctx=>{if(!requireAuth(ctx))return;await ctx.reply('/start\n/status\n/balance\n/wallets\n/create\n/fund\n/buy\n/sell\n/token\n/analytics\n/payout\n/admin');});
bot.command('status',async ctx=>{if(!requireAuth(ctx))return;await ctx.reply(`🟢 Online\nNetwork: Solana Mainnet\nMaster: ${shortKey(masterKeypair.publicKey)}\nMaster SOL: ${(await masterBalance()).toFixed(4)}`);});
bot.command('balance',async ctx=>{if(!requireAuth(ctx))return;const rows=[`Master: ${(await masterBalance()).toFixed(4)} SOL`];for(const w of getWallets())rows.push(`${w.id}: ${(await solBalance(new PublicKey(w.publicKey))).toFixed(4)} SOL`);await ctx.reply(rows.join('\n'));});
bot.command('wallets',async ctx=>{if(!requireAuth(ctx))return;await showWallets(ctx);});
bot.command('create',async ctx=>{if(!requireAuth(ctx))return;sessions.set(uid(ctx),{action:'create-name',data:{}});await ctx.reply('Enter coin name:');});
bot.command('fund',async ctx=>{if(!requireAuth(ctx)||!ownerGuard(ctx))return;sessions.set(uid(ctx),{action:'fund-wallet',data:{}});await ctx.reply('Enter treasury wallet ID (example W1):');});
bot.command('buy',async ctx=>{if(!requireAuth(ctx))return;sessions.set(uid(ctx),{action:'buy-mint',data:{}});await ctx.reply('Enter token mint address:');});
bot.command('sell',async ctx=>{if(!requireAuth(ctx))return;sessions.set(uid(ctx),{action:'sell-mint',data:{}});await ctx.reply('Enter token mint address:');});
bot.command('token',async ctx=>{if(!requireAuth(ctx))return;sessions.set(uid(ctx),{action:'analytics-mint',data:{}});await ctx.reply('Enter token mint address:');});
bot.command('analytics',async ctx=>{if(!requireAuth(ctx))return;sessions.set(uid(ctx),{action:'analytics-mint',data:{}});await ctx.reply('Enter token mint address:');});
bot.command('payout',async ctx=>{if(!requireAuth(ctx)||!ownerGuard(ctx))return;sessions.set(uid(ctx),{action:'payout-amount',data:{}});await ctx.reply(`Enter SOL amount (max ${config.maxPayoutSol}). Destination: ${config.payoutWallet}`);});
bot.command('admin',async ctx=>{if(!requireAuth(ctx)||!ownerGuard(ctx))return;await ctx.reply('⚙️ ADMIN',Markup.inlineKeyboard([[Markup.button.callback('Master Balance','balances'),Markup.button.callback('Create Treasury Wallet','newwallet')],[Markup.button.callback('Fund Treasury','fund'),Markup.button.callback('Payout','payout')]]));});

async function showWallets(ctx:Context){const rows=['👛 Treasury',`Master ${shortKey(masterKeypair.publicKey)} ${(await masterBalance()).toFixed(4)} SOL`];for(const w of getWallets())rows.push(`${w.id} ${shortKey(w.publicKey)} ${(await solBalance(new PublicKey(w.publicKey))).toFixed(4)} SOL`);await ctx.reply(rows.join('\n'),Markup.inlineKeyboard([[Markup.button.callback('Create Wallet','newwallet'),Markup.button.callback('Refresh','balances')]]));}

bot.action('newwallet',async ctx=>{if(!auth(ctx)||!isOwner(ctx))return;const w=createWallet();await ctx.answerCbQuery();await ctx.reply(`✅ Treasury wallet created\nWallet ID: ${w.id}\nAddress: ${w.publicKey}\n⚠️ Controlled by the bot.`);});
bot.action('wallets',async ctx=>{if(!requireAuth(ctx))return;await ctx.answerCbQuery();await showWallets(ctx);});
bot.action('balances',async ctx=>{if(!requireAuth(ctx))return;await ctx.answerCbQuery();const rows=[`Master: ${(await masterBalance()).toFixed(4)} SOL`];for(const w of getWallets())rows.push(`${w.id}: ${(await solBalance(new PublicKey(w.publicKey))).toFixed(4)} SOL`);await ctx.reply(rows.join('\n'));});
bot.action('create',async ctx=>{if(!requireAuth(ctx))return;sessions.set(uid(ctx),{action:'create-name',data:{}});await ctx.answerCbQuery();await ctx.reply('Enter coin name:');});
bot.action('buy',async ctx=>{if(!requireAuth(ctx))return;sessions.set(uid(ctx),{action:'buy-mint',data:{}});await ctx.answerCbQuery();await ctx.reply('Enter token mint address:');});
bot.action('sell',async ctx=>{if(!requireAuth(ctx))return;sessions.set(uid(ctx),{action:'sell-mint',data:{}});await ctx.answerCbQuery();await ctx.reply('Enter token mint address:');});
bot.action('analytics',async ctx=>{if(!requireAuth(ctx))return;sessions.set(uid(ctx),{action:'analytics-mint',data:{}});await ctx.answerCbQuery();await ctx.reply('Enter token mint address:');});
bot.action('payout',async ctx=>{if(!requireAuth(ctx)||!isOwner(ctx))return;sessions.set(uid(ctx),{action:'payout-amount',data:{}});await ctx.answerCbQuery();await ctx.reply(`Enter SOL amount (max ${config.maxPayoutSol}).`);});
bot.action('admin',async ctx=>{if(!requireAuth(ctx)||!isOwner(ctx))return;await ctx.answerCbQuery();await ctx.reply('⚙️ ADMIN',Markup.inlineKeyboard([[Markup.button.callback('Master Balance','balances'),Markup.button.callback('Create Treasury Wallet','newwallet')],[Markup.button.callback('Payout','payout')]]));});

bot.on('text',async ctx=>{if(!auth(ctx))return;const session=sessions.get(uid(ctx));if(!session)return;const text=ctx.message.text.trim();try{
if(session.action==='create-name'){session.data.name=text;session.action='create-symbol';return void ctx.reply('Enter symbol:');}
if(session.action==='create-symbol'){session.data.symbol=text;session.action='create-uri';return void ctx.reply('Enter metadata URI:');}
if(session.action==='create-uri'){new URL(text);session.data.uri=text;session.action='create-buy';return void ctx.reply(`Enter initial buy SOL (0 to ${config.maxSingleBuySol}):`);}
if(session.action==='create-buy'){const n=Number(text);if(!Number.isFinite(n)||n<0||n>config.maxSingleBuySol)throw new Error('Invalid initial buy amount.');session.data.initialBuy=String(n);session.action='create-confirm';return void ctx.reply(`⚠️ CONFIRM TRANSACTION\nCREATE ${session.data.name} (${session.data.symbol})\nInitial buy: ${n} SOL`,Markup.inlineKeyboard([[Markup.button.callback('✅ Confirm','confirm-create'),Markup.button.callback('❌ Cancel','cancel')]]));}
if(session.action==='fund-wallet'){if(!getWallet(text))throw new Error('Wallet not found.');session.data.wallet=text;session.action='fund-amount';return void ctx.reply(`Enter SOL amount (max ${config.maxSingleFundSol}):`);}
if(session.action==='fund-amount'){const n=parsePositive(text);if(n>config.maxSingleFundSol)throw new Error('Funding limit exceeded.');session.data.amount=String(n);session.action='fund-confirm';return void ctx.reply(`⚠️ CONFIRM\nFund ${session.data.wallet} with ${n} SOL?`,Markup.inlineKeyboard([[Markup.button.callback('✅ Confirm','confirm-fund'),Markup.button.callback('❌ Cancel','cancel')]]));}
if(session.action==='buy-mint'){session.data.mint=new PublicKey(text).toBase58();session.action='buy-wallet';return void ctx.reply('Enter treasury wallet ID:');}
if(session.action==='buy-wallet'){if(!getWallet(text))throw new Error('Wallet not found.');session.data.wallet=text;session.action='buy-amount';return void ctx.reply(`Enter SOL amount (max ${config.maxSingleBuySol}):`);}
if(session.action==='buy-amount'){const n=parsePositive(text);if(n>config.maxSingleBuySol)throw new Error('Buy limit exceeded.');const w=getWallet(session.data.wallet)!;const q=await import('./solana.js').then(m=>m.quoteBuy(new PublicKey(session.data.mint),new PublicKey(w.publicKey),n));session.data.amount=String(n);session.action='buy-confirm';return void ctx.reply(`⚠️ CONFIRM TRANSACTION\nBUY\nToken: ${shortKey(session.data.mint)}\nWallet: ${session.data.wallet}\nSOL: ${n}\nEstimated tokens: ${q.tokens.toString()}\nSlippage: ${config.slippagePercent}%`,Markup.inlineKeyboard([[Markup.button.callback('✅ Confirm','confirm-buy'),Markup.button.callback('❌ Cancel','cancel')]]));}
if(session.action==='sell-mint'){session.data.mint=new PublicKey(text).toBase58();session.action='sell-wallet';return void ctx.reply('Enter treasury wallet ID:');}
if(session.action==='sell-wallet'){if(!getWallet(text))throw new Error('Wallet not found.');session.data.wallet=text;session.action='sell-amount';return void ctx.reply('Enter raw token amount to sell:');}
if(session.action==='sell-amount'){const amount=new BN(text);if(amount.lte(new BN(0)))throw new Error('Invalid token amount.');const w=getWallet(session.data.wallet)!;const bal=await tokenBalance(new PublicKey(session.data.mint),new PublicKey(w.publicKey));if(amount.gt(bal))throw new Error('Sell amount exceeds wallet token balance.');session.data.amount=text;session.action='sell-confirm';return void ctx.reply(`⚠️ CONFIRM TRANSACTION\nSELL\nToken: ${shortKey(session.data.mint)}\nWallet: ${session.data.wallet}\nTokens: ${text}\nSlippage: ${config.slippagePercent}%`,Markup.inlineKeyboard([[Markup.button.callback('✅ Confirm','confirm-sell'),Markup.button.callback('❌ Cancel','cancel')]]));}
if(session.action==='analytics-mint'){const a=await tokenAnalytics(new PublicKey(text));return void ctx.reply(`📊 TOKEN ANALYTICS\nMint: ${text}\nGraduated: ${a.complete?'YES':'NO'}\nVirtual SOL reserves: ${a.virtualSol.toString()} lamports\nVirtual token reserves: ${a.virtualToken.toString()}\nTotal supply: ${a.tokenSupply.toString()}\n\nControlled-wallet share is monitoring-only; no automatic rebalancing.`);}
if(session.action==='payout-amount'){if(!isOwner(ctx))throw new Error('Owner-only.');const n=parsePositive(text);if(n>config.maxPayoutSol)throw new Error('Payout limit exceeded.');session.data.amount=text;session.action='payout-confirm';return void ctx.reply(`⚠️ CONFIRM PAYOUT\nAmount: ${n} SOL\nDestination: ${config.payoutWallet}`,Markup.inlineKeyboard([[Markup.button.callback('✅ Confirm','confirm-payout'),Markup.button.callback('❌ Cancel','cancel')]]));}
}catch(e){sessions.delete(uid(ctx));await ctx.reply(`❌ ${fmtError(e)}`);}});

bot.action('cancel',async ctx=>{sessions.delete(uid(ctx));await ctx.answerCbQuery();await ctx.reply('❌ Cancelled.');});
bot.action('confirm-create',async ctx=>{const s=sessions.get(uid(ctx));if(!s||s.action!=='create-confirm')return;await ctx.answerCbQuery();if(locks.has('master'))return void ctx.reply('⏳ A transaction is already being processed.');locks.add('master');try{const r=await createCoin({name:s.data.name,symbol:s.data.symbol,uri:s.data.uri,initialBuySol:Number(s.data.initialBuy)});await ctx.reply(`🚀 COIN CREATED\nName: ${s.data.name}\nSymbol: ${s.data.symbol}\nMint: ${r.mint}\nInitial buy: ${s.data.initialBuy} SOL\nTransaction: ${r.signature}\nSolscan: ${explorerTx(r.signature)}`);}catch(e){await ctx.reply(`❌ Transaction failed\nReason: ${fmtError(e)}`);}finally{locks.delete('master');sessions.delete(uid(ctx));}});
bot.action('confirm-fund',async ctx=>{const s=sessions.get(uid(ctx));if(!s||s.action!=='fund-confirm')return;await ctx.answerCbQuery();if(!ownerGuard(ctx))return;const lock=walletKey(s.data.wallet);if(locks.has(lock))return void ctx.reply('⏳ A transaction is already being processed for this wallet.');locks.add(lock);try{const w=getWallet(s.data.wallet)!;const sig=await sendSol(masterKeypair,new PublicKey(w.publicKey),Number(s.data.amount));await ctx.reply(`✅ Treasury funded\nWallet: ${w.id}\nAmount: ${s.data.amount} SOL\nTransaction: ${sig}\nSolscan: ${explorerTx(sig)}`);}catch(e){await ctx.reply(`❌ Transaction failed\nReason: ${fmtError(e)}`);}finally{locks.delete(lock);sessions.delete(uid(ctx));}});
bot.action('confirm-buy',async ctx=>{const s=sessions.get(uid(ctx));if(!s||s.action!=='buy-confirm')return;await ctx.answerCbQuery();const lock=walletKey(s.data.wallet);if(locks.has(lock))return void ctx.reply('⏳ A transaction is already being processed for this wallet.');locks.add(lock);try{const w=getWallet(s.data.wallet)!;const kp=loadKeypair(s.data.wallet);const sig=await buy(new PublicKey(s.data.mint),kp,Number(s.data.amount));await ctx.reply(`✅ BUY CONFIRMED\nTransaction: ${sig}\nSolscan: ${explorerTx(sig)}`);}catch(e){await ctx.reply(`❌ Transaction failed\nReason: ${fmtError(e)}`);}finally{locks.delete(lock);sessions.delete(uid(ctx));}});
bot.action('confirm-sell',async ctx=>{const s=sessions.get(uid(ctx));if(!s||s.action!=='sell-confirm')return;await ctx.answerCbQuery();const lock=walletKey(s.data.wallet);if(locks.has(lock))return void ctx.reply('⏳ A transaction is already being processed for this wallet.');locks.add(lock);try{const w=getWallet(s.data.wallet)!;const kp=loadKeypair(s.data.wallet);const r=await sell(new PublicKey(s.data.mint),kp,new BN(s.data.amount));await ctx.reply(`✅ SELL CONFIRMED\nExpected SOL: ${(Number(r.expectedSol.toString())/1e9).toFixed(4)}\nTransaction: ${r.signature}\nSolscan: ${explorerTx(r.signature)}`);}catch(e){await ctx.reply(`❌ Transaction failed\nReason: ${fmtError(e)}`);}finally{locks.delete(lock);sessions.delete(uid(ctx));}});
bot.action('confirm-payout',async ctx=>{const s=sessions.get(uid(ctx));if(!s||s.action!=='payout-confirm')return;await ctx.answerCbQuery();if(!ownerGuard(ctx))return;if(locks.has('master'))return void ctx.reply('⏳ A transaction is already being processed.');locks.add('master');try{const sig=await sendSol(masterKeypair,new PublicKey(config.payoutWallet),Number(s.data.amount));await ctx.reply(`✅ PAYOUT SENT\nAmount: ${s.data.amount} SOL\nDestination: ${config.payoutWallet}\nTransaction: ${sig}\nSolscan: ${explorerTx(sig)}`);}catch(e){await ctx.reply(`❌ Transaction failed\nReason: ${fmtError(e)}`);}finally{locks.delete('master');sessions.delete(uid(ctx));}});

(async()=>{console.log('Loading configuration...');console.log('Connecting to Solana...');await connection.getLatestBlockhash();console.log('Checking network...');const {verifyMainnet}=await import('./solana.js');await verifyMainnet();console.log('Loading master wallet...');console.log('Checking master balance...');await masterBalance();console.log('Loading Pump SDK...');console.log('Starting Telegram bot...');await bot.launch();console.log(`🟢 MaterBabe Coin Kirkinator online | Mainnet | Master ${shortKey(masterKeypair.publicKey)}`);})();
process.once('SIGINT',()=>bot.stop('SIGINT'));process.once('SIGTERM',()=>bot.stop('SIGTERM'));
